name: "\U0001F680 Feature request"
description: Suggest an idea for Gearbox
title: "[feat] "
labels: ["enhancement"]
projects: ["warpok-us/gearbox"]   # ← auto-adds issue to org project
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      placeholder: Tell us…
